name: Publish Docker Image

on:
  push:
    branches:
      - 'release'
env:
  TEST_TAG: wideglide/fact_extractor:test

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          cache-from: type=registry,ref=wideglide/fact_extractor:latest
          cache-to: type=inline
      -
        name: Test
        run: |
          docker run --rm --entrypoint /bin/python3 -v "/dev":"/dev" --privileged ${{ env.TEST_TAG }} /usr/local/bin/pytest  -k 'not GenericFS' /opt/app/fact_extractor
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wideglide/fact_extractor:latest,wideglide/fact_extractor:focal
          cache-from: type=registry,ref=wideglide/fact_extractor:latest
          cache-to: type=inline
  run_tests:
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - 
        name: Check for loop devices
        run: ls -l /dev/loop*
      -
        name: Run pytest
        run: |
          docker run --rm --entrypoint /bin/python3 -v "/dev":"/dev" --privileged wideglide/fact_extractor:focal /usr/local/bin/pytest /opt/app/fact_extractor
